// Generated by gencpp from file manipulator_pose_following/DeltaPoseRPY.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_DELTAPOSERPY_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_DELTAPOSERPY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulator_pose_following
{
template <class ContainerAllocator>
struct DeltaPoseRPY_
{
  typedef DeltaPoseRPY_<ContainerAllocator> Type;

  DeltaPoseRPY_()
    : data()  {
    }
  DeltaPoseRPY_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> const> ConstPtr;

}; // struct DeltaPoseRPY_

typedef ::manipulator_pose_following::DeltaPoseRPY_<std::allocator<void> > DeltaPoseRPY;

typedef boost::shared_ptr< ::manipulator_pose_following::DeltaPoseRPY > DeltaPoseRPYPtr;
typedef boost::shared_ptr< ::manipulator_pose_following::DeltaPoseRPY const> DeltaPoseRPYConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulator_pose_following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulator_pose_following/DeltaPoseRPY";
  }

  static const char* value(const ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n"
;
  }

  static const char* value(const ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeltaPoseRPY_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulator_pose_following::DeltaPoseRPY_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_DELTAPOSERPY_H
