// Generated by gencpp from file manipulator_pose_following/InitPoint.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_INITPOINT_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_INITPOINT_H

#include <ros/service_traits.h>


#include <manipulator_pose_following/InitPointRequest.h>
#include <manipulator_pose_following/InitPointResponse.h>


namespace manipulator_pose_following
{

struct InitPoint
{

typedef InitPointRequest Request;
typedef InitPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitPoint
} // namespace manipulator_pose_following


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulator_pose_following::InitPoint > {
  static const char* value()
  {
    return "8cbed0c946766354de767198b507d0e3";
  }

  static const char* value(const ::manipulator_pose_following::InitPoint&) { return value(); }
};

template<>
struct DataType< ::manipulator_pose_following::InitPoint > {
  static const char* value()
  {
    return "manipulator_pose_following/InitPoint";
  }

  static const char* value(const ::manipulator_pose_following::InitPoint&) { return value(); }
};


// service_traits::MD5Sum< ::manipulator_pose_following::InitPointRequest> should match
// service_traits::MD5Sum< ::manipulator_pose_following::InitPoint >
template<>
struct MD5Sum< ::manipulator_pose_following::InitPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::InitPoint >::value();
  }
  static const char* value(const ::manipulator_pose_following::InitPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::InitPointRequest> should match
// service_traits::DataType< ::manipulator_pose_following::InitPoint >
template<>
struct DataType< ::manipulator_pose_following::InitPointRequest>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::InitPoint >::value();
  }
  static const char* value(const ::manipulator_pose_following::InitPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulator_pose_following::InitPointResponse> should match
// service_traits::MD5Sum< ::manipulator_pose_following::InitPoint >
template<>
struct MD5Sum< ::manipulator_pose_following::InitPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::InitPoint >::value();
  }
  static const char* value(const ::manipulator_pose_following::InitPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::InitPointResponse> should match
// service_traits::DataType< ::manipulator_pose_following::InitPoint >
template<>
struct DataType< ::manipulator_pose_following::InitPointResponse>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::InitPoint >::value();
  }
  static const char* value(const ::manipulator_pose_following::InitPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_INITPOINT_H
