// Generated by gencpp from file manipulator_pose_following/InitPointRequest.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_INITPOINTREQUEST_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_INITPOINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulator_pose_following
{
template <class ContainerAllocator>
struct InitPointRequest_
{
  typedef InitPointRequest_<ContainerAllocator> Type;

  InitPointRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , transfer_state(0)  {
    }
  InitPointRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , transfer_state(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef uint8_t _transfer_state_type;
  _transfer_state_type transfer_state;





  typedef boost::shared_ptr< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitPointRequest_

typedef ::manipulator_pose_following::InitPointRequest_<std::allocator<void> > InitPointRequest;

typedef boost::shared_ptr< ::manipulator_pose_following::InitPointRequest > InitPointRequestPtr;
typedef boost::shared_ptr< ::manipulator_pose_following::InitPointRequest const> InitPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulator_pose_following::InitPointRequest_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::InitPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.transfer_state == rhs.transfer_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulator_pose_following::InitPointRequest_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::InitPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulator_pose_following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fb5dff2be17969aff4b1898517fc2bf";
  }

  static const char* value(const ::manipulator_pose_following::InitPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fb5dff2be17969aULL;
  static const uint64_t static_value2 = 0xff4b1898517fc2bfULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulator_pose_following/InitPointRequest";
  }

  static const char* value(const ::manipulator_pose_following::InitPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request fields\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"uint8 transfer_state\n"
;
  }

  static const char* value(const ::manipulator_pose_following::InitPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.transfer_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulator_pose_following::InitPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulator_pose_following::InitPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "transfer_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.transfer_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_INITPOINTREQUEST_H
