// Generated by gencpp from file manipulator_pose_following/MoveHomeRequest.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVEHOMEREQUEST_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVEHOMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulator_pose_following
{
template <class ContainerAllocator>
struct MoveHomeRequest_
{
  typedef MoveHomeRequest_<ContainerAllocator> Type;

  MoveHomeRequest_()
    : max_vel_fact(0.0)
    , max_acc_fact(0.0)  {
    }
  MoveHomeRequest_(const ContainerAllocator& _alloc)
    : max_vel_fact(0.0)
    , max_acc_fact(0.0)  {
  (void)_alloc;
    }



   typedef float _max_vel_fact_type;
  _max_vel_fact_type max_vel_fact;

   typedef float _max_acc_fact_type;
  _max_acc_fact_type max_acc_fact;





  typedef boost::shared_ptr< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveHomeRequest_

typedef ::manipulator_pose_following::MoveHomeRequest_<std::allocator<void> > MoveHomeRequest;

typedef boost::shared_ptr< ::manipulator_pose_following::MoveHomeRequest > MoveHomeRequestPtr;
typedef boost::shared_ptr< ::manipulator_pose_following::MoveHomeRequest const> MoveHomeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.max_vel_fact == rhs.max_vel_fact &&
    lhs.max_acc_fact == rhs.max_acc_fact;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulator_pose_following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e3dd77186dd39b45dd658ce66c915e2";
  }

  static const char* value(const ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e3dd77186dd39b4ULL;
  static const uint64_t static_value2 = 0x5dd658ce66c915e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulator_pose_following/MoveHomeRequest";
  }

  static const char* value(const ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 max_vel_fact\n"
"float32 max_acc_fact\n"
;
  }

  static const char* value(const ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max_vel_fact);
      stream.next(m.max_acc_fact);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveHomeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulator_pose_following::MoveHomeRequest_<ContainerAllocator>& v)
  {
    s << indent << "max_vel_fact: ";
    Printer<float>::stream(s, indent + "  ", v.max_vel_fact);
    s << indent << "max_acc_fact: ";
    Printer<float>::stream(s, indent + "  ", v.max_acc_fact);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVEHOMEREQUEST_H
