// Generated by gencpp from file manipulator_pose_following/MoveHome.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVEHOME_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVEHOME_H

#include <ros/service_traits.h>


#include <manipulator_pose_following/MoveHomeRequest.h>
#include <manipulator_pose_following/MoveHomeResponse.h>


namespace manipulator_pose_following
{

struct MoveHome
{

typedef MoveHomeRequest Request;
typedef MoveHomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveHome
} // namespace manipulator_pose_following


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulator_pose_following::MoveHome > {
  static const char* value()
  {
    return "2b1a8682c27b5174f22f80c985fc7be9";
  }

  static const char* value(const ::manipulator_pose_following::MoveHome&) { return value(); }
};

template<>
struct DataType< ::manipulator_pose_following::MoveHome > {
  static const char* value()
  {
    return "manipulator_pose_following/MoveHome";
  }

  static const char* value(const ::manipulator_pose_following::MoveHome&) { return value(); }
};


// service_traits::MD5Sum< ::manipulator_pose_following::MoveHomeRequest> should match
// service_traits::MD5Sum< ::manipulator_pose_following::MoveHome >
template<>
struct MD5Sum< ::manipulator_pose_following::MoveHomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::MoveHome >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveHomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::MoveHomeRequest> should match
// service_traits::DataType< ::manipulator_pose_following::MoveHome >
template<>
struct DataType< ::manipulator_pose_following::MoveHomeRequest>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::MoveHome >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveHomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulator_pose_following::MoveHomeResponse> should match
// service_traits::MD5Sum< ::manipulator_pose_following::MoveHome >
template<>
struct MD5Sum< ::manipulator_pose_following::MoveHomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::MoveHome >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveHomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::MoveHomeResponse> should match
// service_traits::DataType< ::manipulator_pose_following::MoveHome >
template<>
struct DataType< ::manipulator_pose_following::MoveHomeResponse>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::MoveHome >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveHomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVEHOME_H
