// Generated by gencpp from file manipulator_pose_following/MoveToQuat.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVETOQUAT_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVETOQUAT_H

#include <ros/service_traits.h>


#include <manipulator_pose_following/MoveToQuatRequest.h>
#include <manipulator_pose_following/MoveToQuatResponse.h>


namespace manipulator_pose_following
{

struct MoveToQuat
{

typedef MoveToQuatRequest Request;
typedef MoveToQuatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToQuat
} // namespace manipulator_pose_following


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulator_pose_following::MoveToQuat > {
  static const char* value()
  {
    return "4bfdf7c6ab7ed4c87dc99445fde612ed";
  }

  static const char* value(const ::manipulator_pose_following::MoveToQuat&) { return value(); }
};

template<>
struct DataType< ::manipulator_pose_following::MoveToQuat > {
  static const char* value()
  {
    return "manipulator_pose_following/MoveToQuat";
  }

  static const char* value(const ::manipulator_pose_following::MoveToQuat&) { return value(); }
};


// service_traits::MD5Sum< ::manipulator_pose_following::MoveToQuatRequest> should match
// service_traits::MD5Sum< ::manipulator_pose_following::MoveToQuat >
template<>
struct MD5Sum< ::manipulator_pose_following::MoveToQuatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::MoveToQuat >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveToQuatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::MoveToQuatRequest> should match
// service_traits::DataType< ::manipulator_pose_following::MoveToQuat >
template<>
struct DataType< ::manipulator_pose_following::MoveToQuatRequest>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::MoveToQuat >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveToQuatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulator_pose_following::MoveToQuatResponse> should match
// service_traits::MD5Sum< ::manipulator_pose_following::MoveToQuat >
template<>
struct MD5Sum< ::manipulator_pose_following::MoveToQuatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::MoveToQuat >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveToQuatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::MoveToQuatResponse> should match
// service_traits::DataType< ::manipulator_pose_following::MoveToQuat >
template<>
struct DataType< ::manipulator_pose_following::MoveToQuatResponse>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::MoveToQuat >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveToQuatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVETOQUAT_H
