// Generated by gencpp from file manipulator_pose_following/MoveToQuatResponse.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVETOQUATRESPONSE_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVETOQUATRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulator_pose_following
{
template <class ContainerAllocator>
struct MoveToQuatResponse_
{
  typedef MoveToQuatResponse_<ContainerAllocator> Type;

  MoveToQuatResponse_()
    : reply(0)  {
    }
  MoveToQuatResponse_(const ContainerAllocator& _alloc)
    : reply(0)  {
  (void)_alloc;
    }



   typedef int32_t _reply_type;
  _reply_type reply;





  typedef boost::shared_ptr< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToQuatResponse_

typedef ::manipulator_pose_following::MoveToQuatResponse_<std::allocator<void> > MoveToQuatResponse;

typedef boost::shared_ptr< ::manipulator_pose_following::MoveToQuatResponse > MoveToQuatResponsePtr;
typedef boost::shared_ptr< ::manipulator_pose_following::MoveToQuatResponse const> MoveToQuatResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reply == rhs.reply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulator_pose_following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3d102284a2e84efb923807f61669857";
  }

  static const char* value(const ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3d102284a2e84efULL;
  static const uint64_t static_value2 = 0xb923807f61669857ULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulator_pose_following/MoveToQuatResponse";
  }

  static const char* value(const ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 reply\n"
"\n"
;
  }

  static const char* value(const ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToQuatResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulator_pose_following::MoveToQuatResponse_<ContainerAllocator>& v)
  {
    s << indent << "reply: ";
    Printer<int32_t>::stream(s, indent + "  ", v.reply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVETOQUATRESPONSE_H
