// Generated by gencpp from file manipulator_pose_following/MoveToRPY.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVETORPY_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVETORPY_H

#include <ros/service_traits.h>


#include <manipulator_pose_following/MoveToRPYRequest.h>
#include <manipulator_pose_following/MoveToRPYResponse.h>


namespace manipulator_pose_following
{

struct MoveToRPY
{

typedef MoveToRPYRequest Request;
typedef MoveToRPYResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToRPY
} // namespace manipulator_pose_following


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulator_pose_following::MoveToRPY > {
  static const char* value()
  {
    return "a228832e898673e8095d7a0ddc0283a1";
  }

  static const char* value(const ::manipulator_pose_following::MoveToRPY&) { return value(); }
};

template<>
struct DataType< ::manipulator_pose_following::MoveToRPY > {
  static const char* value()
  {
    return "manipulator_pose_following/MoveToRPY";
  }

  static const char* value(const ::manipulator_pose_following::MoveToRPY&) { return value(); }
};


// service_traits::MD5Sum< ::manipulator_pose_following::MoveToRPYRequest> should match
// service_traits::MD5Sum< ::manipulator_pose_following::MoveToRPY >
template<>
struct MD5Sum< ::manipulator_pose_following::MoveToRPYRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::MoveToRPY >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveToRPYRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::MoveToRPYRequest> should match
// service_traits::DataType< ::manipulator_pose_following::MoveToRPY >
template<>
struct DataType< ::manipulator_pose_following::MoveToRPYRequest>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::MoveToRPY >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveToRPYRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulator_pose_following::MoveToRPYResponse> should match
// service_traits::MD5Sum< ::manipulator_pose_following::MoveToRPY >
template<>
struct MD5Sum< ::manipulator_pose_following::MoveToRPYResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::MoveToRPY >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveToRPYResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::MoveToRPYResponse> should match
// service_traits::DataType< ::manipulator_pose_following::MoveToRPY >
template<>
struct DataType< ::manipulator_pose_following::MoveToRPYResponse>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::MoveToRPY >::value();
  }
  static const char* value(const ::manipulator_pose_following::MoveToRPYResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_MOVETORPY_H
