// Generated by gencpp from file manipulator_pose_following/PlannedPath.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_PLANNEDPATH_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_PLANNEDPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulator_pose_following
{
template <class ContainerAllocator>
struct PlannedPath_
{
  typedef PlannedPath_<ContainerAllocator> Type;

  PlannedPath_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , delta_time(0.0)
    , calc_vel(0.0)  {
    }
  PlannedPath_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , delta_time(0.0)
    , calc_vel(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef float _delta_time_type;
  _delta_time_type delta_time;

   typedef float _calc_vel_type;
  _calc_vel_type calc_vel;





  typedef boost::shared_ptr< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> const> ConstPtr;

}; // struct PlannedPath_

typedef ::manipulator_pose_following::PlannedPath_<std::allocator<void> > PlannedPath;

typedef boost::shared_ptr< ::manipulator_pose_following::PlannedPath > PlannedPathPtr;
typedef boost::shared_ptr< ::manipulator_pose_following::PlannedPath const> PlannedPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulator_pose_following::PlannedPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulator_pose_following::PlannedPath_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::PlannedPath_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.delta_time == rhs.delta_time &&
    lhs.calc_vel == rhs.calc_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulator_pose_following::PlannedPath_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::PlannedPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulator_pose_following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80ec71fca2b6f56267998c14845654ea";
  }

  static const char* value(const ::manipulator_pose_following::PlannedPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80ec71fca2b6f562ULL;
  static const uint64_t static_value2 = 0x67998c14845654eaULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulator_pose_following/PlannedPath";
  }

  static const char* value(const ::manipulator_pose_following::PlannedPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float32 delta_time\n"
"float32 calc_vel\n"
;
  }

  static const char* value(const ::manipulator_pose_following::PlannedPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.delta_time);
      stream.next(m.calc_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannedPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulator_pose_following::PlannedPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulator_pose_following::PlannedPath_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "delta_time: ";
    Printer<float>::stream(s, indent + "  ", v.delta_time);
    s << indent << "calc_vel: ";
    Printer<float>::stream(s, indent + "  ", v.calc_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_PLANNEDPATH_H
