// Generated by gencpp from file manipulator_pose_following/ReplyIntRequest.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_REPLYINTREQUEST_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_REPLYINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulator_pose_following
{
template <class ContainerAllocator>
struct ReplyIntRequest_
{
  typedef ReplyIntRequest_<ContainerAllocator> Type;

  ReplyIntRequest_()
    {
    }
  ReplyIntRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReplyIntRequest_

typedef ::manipulator_pose_following::ReplyIntRequest_<std::allocator<void> > ReplyIntRequest;

typedef boost::shared_ptr< ::manipulator_pose_following::ReplyIntRequest > ReplyIntRequestPtr;
typedef boost::shared_ptr< ::manipulator_pose_following::ReplyIntRequest const> ReplyIntRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace manipulator_pose_following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulator_pose_following/ReplyIntRequest";
  }

  static const char* value(const ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReplyIntRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::manipulator_pose_following::ReplyIntRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_REPLYINTREQUEST_H
