// Generated by gencpp from file manipulator_pose_following/ReplyInt.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_REPLYINT_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_REPLYINT_H

#include <ros/service_traits.h>


#include <manipulator_pose_following/ReplyIntRequest.h>
#include <manipulator_pose_following/ReplyIntResponse.h>


namespace manipulator_pose_following
{

struct ReplyInt
{

typedef ReplyIntRequest Request;
typedef ReplyIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReplyInt
} // namespace manipulator_pose_following


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulator_pose_following::ReplyInt > {
  static const char* value()
  {
    return "a3d102284a2e84efb923807f61669857";
  }

  static const char* value(const ::manipulator_pose_following::ReplyInt&) { return value(); }
};

template<>
struct DataType< ::manipulator_pose_following::ReplyInt > {
  static const char* value()
  {
    return "manipulator_pose_following/ReplyInt";
  }

  static const char* value(const ::manipulator_pose_following::ReplyInt&) { return value(); }
};


// service_traits::MD5Sum< ::manipulator_pose_following::ReplyIntRequest> should match
// service_traits::MD5Sum< ::manipulator_pose_following::ReplyInt >
template<>
struct MD5Sum< ::manipulator_pose_following::ReplyIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::ReplyInt >::value();
  }
  static const char* value(const ::manipulator_pose_following::ReplyIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::ReplyIntRequest> should match
// service_traits::DataType< ::manipulator_pose_following::ReplyInt >
template<>
struct DataType< ::manipulator_pose_following::ReplyIntRequest>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::ReplyInt >::value();
  }
  static const char* value(const ::manipulator_pose_following::ReplyIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulator_pose_following::ReplyIntResponse> should match
// service_traits::MD5Sum< ::manipulator_pose_following::ReplyInt >
template<>
struct MD5Sum< ::manipulator_pose_following::ReplyIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::ReplyInt >::value();
  }
  static const char* value(const ::manipulator_pose_following::ReplyIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::ReplyIntResponse> should match
// service_traits::DataType< ::manipulator_pose_following::ReplyInt >
template<>
struct DataType< ::manipulator_pose_following::ReplyIntResponse>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::ReplyInt >::value();
  }
  static const char* value(const ::manipulator_pose_following::ReplyIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_REPLYINT_H
