// Generated by gencpp from file manipulator_pose_following/SetVelocity.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_SETVELOCITY_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_SETVELOCITY_H

#include <ros/service_traits.h>


#include <manipulator_pose_following/SetVelocityRequest.h>
#include <manipulator_pose_following/SetVelocityResponse.h>


namespace manipulator_pose_following
{

struct SetVelocity
{

typedef SetVelocityRequest Request;
typedef SetVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVelocity
} // namespace manipulator_pose_following


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulator_pose_following::SetVelocity > {
  static const char* value()
  {
    return "db9dc0428873a36d1bd052ccc7f0c504";
  }

  static const char* value(const ::manipulator_pose_following::SetVelocity&) { return value(); }
};

template<>
struct DataType< ::manipulator_pose_following::SetVelocity > {
  static const char* value()
  {
    return "manipulator_pose_following/SetVelocity";
  }

  static const char* value(const ::manipulator_pose_following::SetVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::manipulator_pose_following::SetVelocityRequest> should match
// service_traits::MD5Sum< ::manipulator_pose_following::SetVelocity >
template<>
struct MD5Sum< ::manipulator_pose_following::SetVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::SetVelocity >::value();
  }
  static const char* value(const ::manipulator_pose_following::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::SetVelocityRequest> should match
// service_traits::DataType< ::manipulator_pose_following::SetVelocity >
template<>
struct DataType< ::manipulator_pose_following::SetVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::SetVelocity >::value();
  }
  static const char* value(const ::manipulator_pose_following::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulator_pose_following::SetVelocityResponse> should match
// service_traits::MD5Sum< ::manipulator_pose_following::SetVelocity >
template<>
struct MD5Sum< ::manipulator_pose_following::SetVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_pose_following::SetVelocity >::value();
  }
  static const char* value(const ::manipulator_pose_following::SetVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_pose_following::SetVelocityResponse> should match
// service_traits::DataType< ::manipulator_pose_following::SetVelocity >
template<>
struct DataType< ::manipulator_pose_following::SetVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::manipulator_pose_following::SetVelocity >::value();
  }
  static const char* value(const ::manipulator_pose_following::SetVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_SETVELOCITY_H
