// Generated by gencpp from file manipulator_pose_following/SetVelocityRequest.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_POSE_FOLLOWING_MESSAGE_SETVELOCITYREQUEST_H
#define MANIPULATOR_POSE_FOLLOWING_MESSAGE_SETVELOCITYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulator_pose_following
{
template <class ContainerAllocator>
struct SetVelocityRequest_
{
  typedef SetVelocityRequest_<ContainerAllocator> Type;

  SetVelocityRequest_()
    : velocity(0.0)  {
    }
  SetVelocityRequest_(const ContainerAllocator& _alloc)
    : velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelocityRequest_

typedef ::manipulator_pose_following::SetVelocityRequest_<std::allocator<void> > SetVelocityRequest;

typedef boost::shared_ptr< ::manipulator_pose_following::SetVelocityRequest > SetVelocityRequestPtr;
typedef boost::shared_ptr< ::manipulator_pose_following::SetVelocityRequest const> SetVelocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator1> & lhs, const ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulator_pose_following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4ff88b32504f688ULL;
  static const uint64_t static_value2 = 0x719a85e0753f63ceULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulator_pose_following/SetVelocityRequest";
  }

  static const char* value(const ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 velocity\n"
;
  }

  static const char* value(const ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVelocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulator_pose_following::SetVelocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATOR_POSE_FOLLOWING_MESSAGE_SETVELOCITYREQUEST_H
