// Generated by gencpp from file path_control/EndEffectorState.msg
// DO NOT EDIT!


#ifndef PATH_CONTROL_MESSAGE_ENDEFFECTORSTATE_H
#define PATH_CONTROL_MESSAGE_ENDEFFECTORSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Quaternion.h>
#include <sensor_msgs/JointState.h>

namespace path_control
{
template <class ContainerAllocator>
struct EndEffectorState_
{
  typedef EndEffectorState_<ContainerAllocator> Type;

  EndEffectorState_()
    : position()
    , orientation()
    , joint()  {
    }
  EndEffectorState_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , orientation(_alloc)
    , joint(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joint_type;
  _joint_type joint;





  typedef boost::shared_ptr< ::path_control::EndEffectorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_control::EndEffectorState_<ContainerAllocator> const> ConstPtr;

}; // struct EndEffectorState_

typedef ::path_control::EndEffectorState_<std::allocator<void> > EndEffectorState;

typedef boost::shared_ptr< ::path_control::EndEffectorState > EndEffectorStatePtr;
typedef boost::shared_ptr< ::path_control::EndEffectorState const> EndEffectorStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_control::EndEffectorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_control::EndEffectorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_control::EndEffectorState_<ContainerAllocator1> & lhs, const ::path_control::EndEffectorState_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation &&
    lhs.joint == rhs.joint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_control::EndEffectorState_<ContainerAllocator1> & lhs, const ::path_control::EndEffectorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_control::EndEffectorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_control::EndEffectorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_control::EndEffectorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_control::EndEffectorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_control::EndEffectorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_control::EndEffectorState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_control::EndEffectorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40115f38ef3079bbc7172e457d79d145";
  }

  static const char* value(const ::path_control::EndEffectorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40115f38ef3079bbULL;
  static const uint64_t static_value2 = 0xc7172e457d79d145ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_control::EndEffectorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_control/EndEffectorState";
  }

  static const char* value(const ::path_control::EndEffectorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_control::EndEffectorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position   # x, y, z\n"
"geometry_msgs/Quaternion orientation  # w, x, y, z\n"
"sensor_msgs/JointState joint\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::path_control::EndEffectorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_control::EndEffectorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EndEffectorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_control::EndEffectorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_control::EndEffectorState_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "joint: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.joint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_CONTROL_MESSAGE_ENDEFFECTORSTATE_H
