// Generated by gencpp from file path_control/MoveToFirstPosition.msg
// DO NOT EDIT!


#ifndef PATH_CONTROL_MESSAGE_MOVETOFIRSTPOSITION_H
#define PATH_CONTROL_MESSAGE_MOVETOFIRSTPOSITION_H

#include <ros/service_traits.h>


#include <path_control/MoveToFirstPositionRequest.h>
#include <path_control/MoveToFirstPositionResponse.h>


namespace path_control
{

struct MoveToFirstPosition
{

typedef MoveToFirstPositionRequest Request;
typedef MoveToFirstPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToFirstPosition
} // namespace path_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_control::MoveToFirstPosition > {
  static const char* value()
  {
    return "4b55fa8d67c0f416a417d03da8d3ff7f";
  }

  static const char* value(const ::path_control::MoveToFirstPosition&) { return value(); }
};

template<>
struct DataType< ::path_control::MoveToFirstPosition > {
  static const char* value()
  {
    return "path_control/MoveToFirstPosition";
  }

  static const char* value(const ::path_control::MoveToFirstPosition&) { return value(); }
};


// service_traits::MD5Sum< ::path_control::MoveToFirstPositionRequest> should match
// service_traits::MD5Sum< ::path_control::MoveToFirstPosition >
template<>
struct MD5Sum< ::path_control::MoveToFirstPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_control::MoveToFirstPosition >::value();
  }
  static const char* value(const ::path_control::MoveToFirstPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_control::MoveToFirstPositionRequest> should match
// service_traits::DataType< ::path_control::MoveToFirstPosition >
template<>
struct DataType< ::path_control::MoveToFirstPositionRequest>
{
  static const char* value()
  {
    return DataType< ::path_control::MoveToFirstPosition >::value();
  }
  static const char* value(const ::path_control::MoveToFirstPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_control::MoveToFirstPositionResponse> should match
// service_traits::MD5Sum< ::path_control::MoveToFirstPosition >
template<>
struct MD5Sum< ::path_control::MoveToFirstPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_control::MoveToFirstPosition >::value();
  }
  static const char* value(const ::path_control::MoveToFirstPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_control::MoveToFirstPositionResponse> should match
// service_traits::DataType< ::path_control::MoveToFirstPosition >
template<>
struct DataType< ::path_control::MoveToFirstPositionResponse>
{
  static const char* value()
  {
    return DataType< ::path_control::MoveToFirstPosition >::value();
  }
  static const char* value(const ::path_control::MoveToFirstPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_CONTROL_MESSAGE_MOVETOFIRSTPOSITION_H
