// Generated by gencpp from file path_control/MoveToPosition.msg
// DO NOT EDIT!


#ifndef PATH_CONTROL_MESSAGE_MOVETOPOSITION_H
#define PATH_CONTROL_MESSAGE_MOVETOPOSITION_H

#include <ros/service_traits.h>


#include <path_control/MoveToPositionRequest.h>
#include <path_control/MoveToPositionResponse.h>


namespace path_control
{

struct MoveToPosition
{

typedef MoveToPositionRequest Request;
typedef MoveToPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToPosition
} // namespace path_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_control::MoveToPosition > {
  static const char* value()
  {
    return "ef814b4102028e360f0cb6df9fa221a9";
  }

  static const char* value(const ::path_control::MoveToPosition&) { return value(); }
};

template<>
struct DataType< ::path_control::MoveToPosition > {
  static const char* value()
  {
    return "path_control/MoveToPosition";
  }

  static const char* value(const ::path_control::MoveToPosition&) { return value(); }
};


// service_traits::MD5Sum< ::path_control::MoveToPositionRequest> should match
// service_traits::MD5Sum< ::path_control::MoveToPosition >
template<>
struct MD5Sum< ::path_control::MoveToPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_control::MoveToPosition >::value();
  }
  static const char* value(const ::path_control::MoveToPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_control::MoveToPositionRequest> should match
// service_traits::DataType< ::path_control::MoveToPosition >
template<>
struct DataType< ::path_control::MoveToPositionRequest>
{
  static const char* value()
  {
    return DataType< ::path_control::MoveToPosition >::value();
  }
  static const char* value(const ::path_control::MoveToPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_control::MoveToPositionResponse> should match
// service_traits::MD5Sum< ::path_control::MoveToPosition >
template<>
struct MD5Sum< ::path_control::MoveToPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_control::MoveToPosition >::value();
  }
  static const char* value(const ::path_control::MoveToPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_control::MoveToPositionResponse> should match
// service_traits::DataType< ::path_control::MoveToPosition >
template<>
struct DataType< ::path_control::MoveToPositionResponse>
{
  static const char* value()
  {
    return DataType< ::path_control::MoveToPosition >::value();
  }
  static const char* value(const ::path_control::MoveToPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_CONTROL_MESSAGE_MOVETOPOSITION_H
