// Generated by gencpp from file path_control/MoveToFirstPositionResponse.msg
// DO NOT EDIT!


#ifndef PATH_CONTROL_MESSAGE_MOVETOFIRSTPOSITIONRESPONSE_H
#define PATH_CONTROL_MESSAGE_MOVETOFIRSTPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_control
{
template <class ContainerAllocator>
struct MoveToFirstPositionResponse_
{
  typedef MoveToFirstPositionResponse_<ContainerAllocator> Type;

  MoveToFirstPositionResponse_()
    : reached(false)  {
    }
  MoveToFirstPositionResponse_(const ContainerAllocator& _alloc)
    : reached(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reached_type;
  _reached_type reached;





  typedef boost::shared_ptr< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToFirstPositionResponse_

typedef ::path_control::MoveToFirstPositionResponse_<std::allocator<void> > MoveToFirstPositionResponse;

typedef boost::shared_ptr< ::path_control::MoveToFirstPositionResponse > MoveToFirstPositionResponsePtr;
typedef boost::shared_ptr< ::path_control::MoveToFirstPositionResponse const> MoveToFirstPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_control::MoveToFirstPositionResponse_<ContainerAllocator1> & lhs, const ::path_control::MoveToFirstPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reached == rhs.reached;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_control::MoveToFirstPositionResponse_<ContainerAllocator1> & lhs, const ::path_control::MoveToFirstPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80204a6ff2622a7071680d5597cbd3aa";
  }

  static const char* value(const ::path_control::MoveToFirstPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80204a6ff2622a70ULL;
  static const uint64_t static_value2 = 0x71680d5597cbd3aaULL;
};

template<class ContainerAllocator>
struct DataType< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_control/MoveToFirstPositionResponse";
  }

  static const char* value(const ::path_control::MoveToFirstPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reached\n"
"\n"
;
  }

  static const char* value(const ::path_control::MoveToFirstPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToFirstPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_control::MoveToFirstPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_control::MoveToFirstPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_CONTROL_MESSAGE_MOVETOFIRSTPOSITIONRESPONSE_H
