// Generated by gencpp from file path_control/MoveToPositionRequest.msg
// DO NOT EDIT!


#ifndef PATH_CONTROL_MESSAGE_MOVETOPOSITIONREQUEST_H
#define PATH_CONTROL_MESSAGE_MOVETOPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_control
{
template <class ContainerAllocator>
struct MoveToPositionRequest_
{
  typedef MoveToPositionRequest_<ContainerAllocator> Type;

  MoveToPositionRequest_()
    : target_positions()
    , duration(0.0)  {
    }
  MoveToPositionRequest_(const ContainerAllocator& _alloc)
    : target_positions(_alloc)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _target_positions_type;
  _target_positions_type target_positions;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::path_control::MoveToPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_control::MoveToPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPositionRequest_

typedef ::path_control::MoveToPositionRequest_<std::allocator<void> > MoveToPositionRequest;

typedef boost::shared_ptr< ::path_control::MoveToPositionRequest > MoveToPositionRequestPtr;
typedef boost::shared_ptr< ::path_control::MoveToPositionRequest const> MoveToPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_control::MoveToPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_control::MoveToPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_control::MoveToPositionRequest_<ContainerAllocator1> & lhs, const ::path_control::MoveToPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_positions == rhs.target_positions &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_control::MoveToPositionRequest_<ContainerAllocator1> & lhs, const ::path_control::MoveToPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_control::MoveToPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_control::MoveToPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_control::MoveToPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_control::MoveToPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_control::MoveToPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_control::MoveToPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_control::MoveToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30b4649adaa49810130ba13f74e336f8";
  }

  static const char* value(const ::path_control::MoveToPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30b4649adaa49810ULL;
  static const uint64_t static_value2 = 0x130ba13f74e336f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_control::MoveToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_control/MoveToPositionRequest";
  }

  static const char* value(const ::path_control::MoveToPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_control::MoveToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] target_positions  # Desired joint positions\n"
"float64 duration            # Time to reach the target positions\n"
;
  }

  static const char* value(const ::path_control::MoveToPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_control::MoveToPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_positions);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_control::MoveToPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_control::MoveToPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_positions[]" << std::endl;
    for (size_t i = 0; i < v.target_positions.size(); ++i)
    {
      s << indent << "  target_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.target_positions[i]);
    }
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_CONTROL_MESSAGE_MOVETOPOSITIONREQUEST_H
